### ISSUE TITLE
codeserver のターミナルで bash が起動しない

### ISSUE THREAD

**Issue by tenzen-y** [KindaiCVLAB/machinelearning-images#22]
codeserver のターミナルがデフォルトで bash が起動せず，/bin/sh が起動する．

**Comment by newFuHi** [comment]
@tenzen-y こういうのってcodeserverのところとかを見たらなんとかなりますか？

**Comment by tenzen-y** [comment]
@newFuHi 
多分，[ここ](https://github.com/KindaiCVLAB/machinelearning-images/tree/master/configs/vscode)の書式に変更があったのだと思うから vscode のドキュメント読めばわかると思う．
